### ISSUE TITLE
Error while running R/readTems.R 

### ISSUE THREAD

**Issue by TobiasKor** [debruine/frlgmm#1]
Hi, 
Whilst running the readTems function I received this error message: 

Error in dimnames(specimens)[[3]] <- dnames[[1]] : 
  length of 'dimnames' [3] not equal to array extent

The code I ran was the following:
readTems("[...]", semi.landmarks = 0, analyse = TRUE, method = "broken-stick")
It says it has found 145 Tem files - but next above error message is shown. 

Does anyone know what is wrong with the code I am running or the data I put in?

Thanks in advance!
Tobias

**Comment by debruine** [comment]
I'll look into this. Can you send me 1 or 2 of your tem files?

**Comment by TobiasKor** [comment]
Sure, here you go - we've got one set with the whole "facial mask" set (0001_aligned_179.tem) and another set with 14 landmarks (0001_aligned_14.tem).

Thank you!

[2 template files.zip](https://github.com/debruine/frlgmm/files/1119288/2.template.files.zip)

**Comment by TobiasKor** [comment]
Dear @debruine,
Are there any news regarding the error with the readTems function I mentioned in my earlier post? 
I'd appreciate any help, since it would greatly simplify exporting our landmark data.
Best,
Tobias

**Comment by TobiasKor** [comment]
We just solved the issue with the help of @rubenarslan. It appeared we had to manually install an earlier version of geomorph (3.0.1). If you'd like further detail, just give me a shout.
Best,
Tobias

**Comment by debruine** [comment]
Sorry to be so slow! The new geomorph `arrayspec` function takes the coordinates in a different order and it took me awhile to figure this out. It's sorted now and the files are updated. It probably won't work with the old geomorph now.

**Comment by TobiasKor** [comment]
OK, thanks for that!
